tls_server_config:
  cert_file: /etc/node_exporter/node_exporter.crt
  key_file: /etc/node_exporter/node_exporter.key
basic_auth_users:
  prometheus: $2y$12$zwyQ0z4DwXH/07QtrqRYvew82DeLYq8sUiUxHOxsl6o3X8jmbQw.K
